server:
    port: 8082

logging:
    level:
        org.springframework.web.client.RestTemplate: DEBUG

spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: <stuff>
                        client-secret:  <stuff>